event:
  flight: true
  move: true
  command: true

blacklist-command-list:
  - "/res tp"
  - "/tp"
  - "/spawn"
  - "/back"
  - "/warp"

message:
  turn-on: "&aYou entered a residence area. Fly is turned on."
  turn-off: "&cYou left the residence area. Fly is turned off."
  no-command: "&cPlease drop on ground before using this command."